version: '3.0'
services:
    Java:
        build: /var/lib/jenkins/workspace/prod_crm
        container_name: prodcrm
        image: prod_crm
        networks:
            - java_connect
        ports:
            - 5003:5003
        restart: always
        environment:
           - DB_USERNAME=${DB_USERNAME}
           - DB_PASSWORD=${DB_PASSWORD}
           - DB_URL=${DB_URL}
networks:
    java_connect:
        external: true
