version: '3.0'
services:
    Java:
        build: /root/jenkins/workspace/prod_crm
        container_name: prodcrm
        image: prod_crm
        networks:
            - java_connect
        ports:
            - 3003:8080
        restart: always          
networks:
    java_connect:
        external: true
